# Generated by Django 3.0.5 on 2020-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=5),
        ),
    ]
